import { 
  mdiClose, 
  mdiHome, 
  mdiEyeOff, 
  mdiEye,
  mdiArrowLeft,
  mdiDownload,
  mdiCheckCircle,
  mdiCloseCircle,
  mdiContentSave,
  mdiMenu,
  mdiMenuOpen,
  mdiClipboardList,
  mdiTrophy,
  mdiMagnify,
  mdiHelpCircleOutline,
  mdiHelpCircle,
  mdiWallet,
  mdiRefresh,
  mdiAlertCircle,
  mdiContentCopy,
  mdiInformation,
  mdiAccount,
  mdiFileSearchOutline,
  mdiAlert,
  mdiLightbulb
} from '@mdi/js';

export const icons = {
  close: mdiClose,
  home: mdiHome,
  eyeOff: mdiEyeOff,
  eye: mdiEye,
  arrowLeft: mdiArrowLeft,
  download: mdiDownload,
  checkCircle: mdiCheckCircle,
  closeCircle: mdiCloseCircle,
  contentSave: mdiContentSave,
  menu: mdiMenu,
  menuOpen: mdiMenuOpen,
  clipboardList: mdiClipboardList,
  trophy: mdiTrophy,
  magnify: mdiMagnify,
  helpCircleOutline: mdiHelpCircleOutline,
  helpCircle: mdiHelpCircle,
  wallet: mdiWallet,
  refresh: mdiRefresh,
  alertCircle: mdiAlertCircle,
  contentCopy: mdiContentCopy,
  information: mdiInformation,
  account: mdiAccount,
  fileSearchOutline: mdiFileSearchOutline,
  alert: mdiAlert,
  lightbulb: mdiLightbulb
};
